FROM node:20-bookworm-slim

RUN apt-get update && \
    apt-get install -y python3 make g++ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install --production --build-from-source

COPY . .

EXPOSE 3001

CMD ["node", "wa_server.js"]